### PR TITLE
Fixed opening missions menu when there are per island missions

### LINKED ISSUE #2569: /is mission accessible without island
### Minecraft's Version

1.21.7

### Plugin's Version

SuperiorSkyblock2-2025.1-b548

### Describe the bug

Hello, when i've not island i'm able to do /island missions and it will display empty menu without any mission maybe you can add an message when player doesn't have island ? 

### To Reproduce

Disband your island and do /is mission

### Additional Information

I use also SSB Bridge idk if it's linked

### PR DESCRIPTION
**Pull request by Lemvs**
Fixes #2569

### CODE REVIEW

File: src/main/java/com/bgsoftware/superiorskyblock/core/menu/button/impl/OpenMissionCategoryButton.java [hunk 1]
```diff
@@ -28,6 +30,13 @@ public Template getTemplate() {
 
     @Override
     public void onButtonClick(InventoryClickEvent clickEvent) {
+        boolean requireIsland = getTemplate().missionCategory.getMissions().stream().allMatch(Mission::getIslandMission);
```
Comment (OmerBenGera) [inline src/main/java/com/bgsoftware/superiorskyblock/core/menu/button/impl/OpenMissionCategoryButton.java]: This value is computed every button click. Instead, it is better to cache it once per menu view.

**Review by OmerBenGera — APPROVED** [review]
